INSERT INTO dropdown_options (category, value, label, css_class, sort_order) VALUES
('item', 'cctv', 'CCTV / Security Camera', 'font-bold text-slate-700', 28),
('item', 'access_control', 'Access Control / Card Reader', 'font-bold text-slate-700', 29),
('item', 'fire_alarm', 'Fire Alarm / Smoke Detector', 'font-bold text-slate-700', 30),
('item', 'fire_extinguisher', 'Fire Extinguisher', 'font-bold text-slate-700', 31),
('item', 'elevator', 'Elevator / Lift', 'font-bold text-slate-700', 32),
('item', 'staircase', 'Staircase / Handrail', 'font-bold text-slate-700', 33),
('item', 'roof', 'Roof / Gutter', 'font-bold text-slate-700', 34),
('item', 'pipe', 'Pipe / Plumbing Fixture', 'font-bold text-slate-700', 35),
('item', 'water_dispenser', 'Water Dispenser / Cooler', 'font-bold text-slate-700', 36),
('item', 'microwave', 'Microwave / Kitchen Appliance', 'font-bold text-slate-700', 37),
('item', 'refrigerator', 'Refrigerator', 'font-bold text-slate-700', 38),
('item', 'lab_equipment', 'Laboratory Equipment', 'font-bold text-slate-700', 39),
('item', 'workshop_tool', 'Workshop Tool / Machinery', 'font-bold text-slate-700', 40),
('item', 'sports_equipment', 'Sports Equipment / Gym Gear', 'font-bold text-slate-700', 41),
('item', 'locker', 'Locker / Wardrobe', 'font-bold text-slate-700', 42),
('item', 'blinds', 'Blinds / Curtains', 'font-bold text-slate-700', 43),
('item', 'carpet', 'Carpet / Rug', 'font-bold text-slate-700', 44),
('item', 'signage', 'Signage / Notice Board', 'font-bold text-slate-700', 45),
('item', 'telephone', 'Telephone / Intercom', 'font-bold text-slate-700', 46),
('item', 'clock_bell', 'Clock / Bell System', 'font-bold text-slate-700', 47);
